management:
    endpoint:
        health:
            show-components: always
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    error:
        include-binding-errors: always
        include-exception: true
        include-message: always
    port: ${app.port:10000}
spring:
    application:
        name: agreement
    config:
        import: configserver:http://127.0.0.1:8888
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 123456
        url: jdbc:postgresql://localhost:5432/playground
        username: postgres
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                archive:
                    autodetection: class, hbm
                connection:
                    release_mode: auto
                default_batch_fetch_size: 1000
                dialect: org.hibernate.dialect.PostgreSQLDialect
                enable_lazy_load_no_trans: true
                format_sql: false
                id:
                    new_generator_mappings: true
                jdbc:
                    batch_size: 1000
                    batch_versioned_data: true
                    fetch_size: 1000
                    lob:
                        non_contextual_creation: true
                order_inserts: true
                order_updates: true
                show_sql: false
    security:
        user:
            name: osman
            password: 123456
resilience4j:
    retry:
        instances:
          claimRetry:
              max-attempts: 3
              wait-duration: 10ms
#              retry-exceptions:
#                - org.springframework.web.client.RestClientException
              result-predicate: com.micro.training.msagreement.integration.error.ClaimRetryPredicate
              retry-exception-predicate: com.micro.training.msagreement.integration.error.ClaimExceptionPredicate
    circuitbreaker:
        instances:
          claimCC:
            sliding-window-type: count-based
            sliding-window-size: 20
            minimum-number-of-calls: 10
            failure-rate-threshold: 30
            wait-duration-in-open-state: '4s'
            automatic-transition-from-open-to-half-open-enabled: false
            permitted-number-of-calls-in-half-open-state: 10
            max-wait-duration-in-half-open-state: '10s'
            slow-call-duration-threshold: 500
            slow-call-rate-threshold: 50
